USE capgemini_arg;
SELECT  emp.LAST_NAME,  dep.DEPARTMENT_NAME, LOC.CITY
FROM employees EMP 
JOIN departments DEP ON dep.DEPARTMENT_ID = emp.DEPARTMENT_ID
JOIN locations LOC ON dep.LOCATION_ID = loc.LOCATION_ID
where COUNTRY_ID = 'UK' AND EMP.COMMISSION_PCT IS NOT NULL