USE capgemini_arg;
INSERT INTO departments
SELECT DEP.DEPARTMENT_ID+200, CONCAT (DEP.DEPARTMENT_NAME, 'Y', LOC.COUNTRY_ID), DEP.MANAGER_ID, DLOC.LOCATION_ID
FROM departments DEP
INNER JOIN locations LOC
ON DEP.LOCATION_ID = LOC.LOCATION_ID