USE capgemini_arg;
SELECT HIRE_DATE, DEPARTMENT_ID
FROM employees
WHERE HIRE_DATE = '1987-06-17'; -- CAMBIE FECHA PUES NO EXISTE LA OTRA
SELECT DEPARTMENT_ID, COUNT( DEPARTMENT_ID )
FROM employees
GROUP BY DEPARTMENT_ID; -- ID 50

UPDATE employees 
SET DEPARTMENT_ID = 50
WHERE HIRE_DATE = '1987-06-17'

