USE capgemini_arg;
SELECT LOC.COUNTRY_ID, DEP.DEPARTMENT_ID, EMP.EMPLOYEE_ID
FROM employees EMP 
JOIN departments DEP ON dep.DEPARTMENT_ID = EMP.DEPARTMENT_ID
JOIN locations LOC ON dep.LOCATION_ID = loc.LOCATION_ID
WHERE COUNTRY_ID = 'CA';

DELETE FROM EMPLOYEES
WHERE DEPARTMENT_ID = '20';

DELETE FROM departments
WHERE DEPARTMENT_ID = '20'