USE capgemini_arg;
SELECT DISTINCT DEPARTMENT_ID
FROM employees order by DEPARTMENT_ID; -- ULTIMO REGISTRO DEPARTMENT_ID ES 110
SELECT DISTINCT DEPARTMENT_ID
FROM employees order by DEPARTMENT_ID DESC; 