USE capgemini_arg;
SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_NAME, SALARY, COMMISSION_PCT
FROM employees AS emp INNER JOIN departments AS dep
ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID
WHERE (COMMISSION_PCT IS NULL OR COMMISSION_PCT = 0) AND
(SALARY BETWEEN 7000 AND 10000)  -- (SALARY <= 10000 AND  SALARY >= 7000)

