USE capgemini_arg;
-- SELECT * from employees;
SELECT DEPARTMENT_ID, SALARY FROM (
    SELECT DEPARTMENT_ID,MAX(SALARY) SALARY
      FROM EMPLOYEES
      GROUP BY 1  ) 
      A JOIN EMPLOYEES USING(SALARY,DEPARTMENT_ID)
  WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);